name: Upload Assets

on:
  push:
    branches:
      - fix/workflow

    paths:
    - 'resources/**'
    - '!resources/lang/**'

jobs:
    Build-Upload:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [10.x]

      steps:
        - name: Checkout repository
          uses: actions/checkout@v1

        - name: Build
          run: |
            yarn install
            yarn prod
        
        - name: Upload
          uses: appleboy/scp-action@master
          with:
            host: 159.65.136.231
            username: root
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            source: "public/css,public/js,public/mix-manifest.json"
            target: "/var/www/site"
